#!/usr/bin/env python3
"""Maintainer-only OpenPBR WGSL/LUT generation; never downloads or runs from consumer builds."""
import argparse
import hashlib
import json
import pathlib
import re
import struct
import subprocess
import tempfile

ROOT = pathlib.Path(__file__).resolve().parents[2]
HERE = pathlib.Path(__file__).resolve().parent
MANIFEST = json.loads((HERE / "manifest.json").read_text())
SHADER_NOTICE = (
    "// Generated by eng/openpbr/generate.py with Slang 2026.14. Do not edit directly.\n"
    "// Derived from Adobe OpenPBR BSDF 1.1.1, Copyright 2026 Adobe, Apache-2.0.\n"
    "// Pinned source: c91aad1d1ce1693e803f039d7c92c2965c4eb013.\n"
    "// Mu3D adds resource adapters and entry points; see accompanying Adobe-LICENSE and NOTICE.md.\n\n"
).encode("utf-8")


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def validate_inputs():
    source = HERE / "upstream"
    expected = MANIFEST["upstream"]["files"]
    actual = {p.relative_to(source).as_posix() for p in source.rglob("*") if p.is_file()}
    if actual != set(expected):
        raise ValueError("The pinned upstream source file inventory has changed.")
    for name, checksum in expected.items():
        # Git may check these text-only vendored files out as CRLF on Windows.
        # Pins describe the upstream LF payload; compiler/binary pins stay byte-exact.
        if hashlib.sha256((source / name).read_bytes().replace(b"\r\n", b"\n")).hexdigest() != checksum:
            raise ValueError(f"Pinned upstream checksum mismatch: {name}")
    return source


def validate_compiler(path):
    path = path.resolve()
    candidates = MANIFEST["compiler"]["assets"].values()
    match = next((x for x in candidates if x["executableSha256"] == digest(path)), None)
    if match is None:
        raise ValueError("The compiler is not a verified binary from the pinned Slang release.")
    library = path.parent / match.get("libraryPath", "../lib/libslang.dylib")
    if digest(library) != match["librarySha256"]:
        raise ValueError("Pinned Slang library checksum mismatch.")
    version = subprocess.check_output([str(path), "-version"], text=True, stderr=subprocess.STDOUT).strip()
    if version != MANIFEST["compiler"]["version"]:
        raise ValueError(f"Wrong Slang version: {version}")
    return path


def f32(value):
    return struct.unpack("<f", struct.pack("<f", value))[0]


def lookup_bytes(source):
    names = [
        ("ideal_dielectric_energy_complement", 32768),
        ("ideal_dielectric_avg_energy_complement", 1024),
        ("ideal_dielectric_reflection_ratio", 1024),
        ("opaque_dielectric_energy_complement", 32768),
        ("opaque_dielectric_avg_energy_complement", 1024),
        ("ideal_metal_energy_complement", 1024),
        ("ideal_metal_avg_energy_complement", 32),
    ]
    values = []
    data = source / "impl" / "data"
    inverse_unorm = f32(1 / 65535)
    for name, count in names:
        text = re.sub(r"//[^\n]*", "", (data / f"openpbr_{name}_data.h").read_text())
        raw = [int(x) for x in re.findall(r"\d+", text)]
        if len(raw) != count or any(x < 0 or x > 65535 for x in raw):
            raise ValueError(f"Invalid pinned lookup table: {name}")
        # Match upstream float(uint16) * float(1 / 65535), including each FP32 rounding.
        values.extend(f32(x * inverse_unorm) for x in raw)
    text = re.sub(r"//[^\n]*", "", (data / "openpbr_ltc_data.h").read_text())
    ltc = [float(x.strip()) for v in re.findall(r"vec3\(([^)]+)\)", text) for x in v.split(",")]
    if len(ltc) != 3072:
        raise ValueError("Invalid pinned LTC table.")
    values.extend(ltc)
    if len(values) != MANIFEST["configuration"]["lookupFloatCount"]:
        raise ValueError("Lookup buffer length disagrees with the fixed shader layout.")
    return struct.pack("<" + "f" * len(values), *values)


def write_or_check(destination, data, check):
    if check:
        if not destination.exists() or destination.read_bytes() != data:
            raise ValueError(f"Generated artifact is stale: {destination.relative_to(ROOT)}")
    else:
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_bytes(data)
    print(f"{'Verified' if check else 'Generated'} {destination.relative_to(ROOT)} ({len(data)} bytes)")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--slangc", type=pathlib.Path, help="Verified maintainer compiler; never auto-installed.")
    parser.add_argument("--validate-input-pins", action="store_true", help="Only verify the vendored upstream files.")
    parser.add_argument("--check", action="store_true", help="Compare generated bytes without modifying the repository.")
    parser.add_argument("--shader", choices=("all", "render", "reference", "fast", "raster"), default="all")
    args = parser.parse_args()
    source = validate_inputs()
    print(f"Verified {len(MANIFEST['upstream']['files'])} unchanged upstream files.")
    if args.validate_input_pins:
        return
    if args.slangc is None:
        parser.error("--slangc is required for maintainer generation.")
    compiler = validate_compiler(args.slangc)
    targets = {
        "render": ROOT / "src/Mu3D.Rendering.OpenPbr/Shaders/render.wgsl",
        "raster": ROOT / "src/Mu3D.Rendering.OpenPbr/Shaders/raster.wgsl",
        "reference": ROOT / "tests/Mu3D.OpenPbr.Rendering.Tests/Shaders/reference.wgsl",
        "fast": ROOT / "src/Mu3D.Rendering.OpenPbr/Shaders/fast.wgsl",
    }
    write_or_check(ROOT / "src/Mu3D.Rendering.OpenPbr/Shaders/Lut.bin", lookup_bytes(source), args.check)
    with tempfile.TemporaryDirectory(prefix="mu3d-openpbr-gen-") as temporary:
        for name, destination in targets.items():
            if args.shader not in ("all", name):
                continue
            output = pathlib.Path(temporary) / f"{name}.wgsl"
            subprocess.run([
                str(compiler), str(HERE / f"{name}.slang"), "-I", str(source),
                "-I", str(ROOT / "tests/Mu3D.OpenPbr.Tests/Reference"),
                "-target", "wgsl", "-entry", "main", "-stage", "fragment", "-o", str(output),
            ], check=True)
            write_or_check(destination, SHADER_NOTICE + output.read_bytes(), args.check)


if __name__ == "__main__":
    main()
