#!/usr/bin/env python3
"""Maintainer-only OCIO 2.5.2 exact processor export. No downloads or consumer build hooks."""
import argparse, hashlib, json, pathlib, re, subprocess, tempfile
ROOT=pathlib.Path(__file__).resolve().parents[2]
OUT=ROOT/'src/Mu3D.Color/ColorViews/Generated'
ENG=ROOT/'eng/color-management'
XYZ=[3.2409699419045226,-1.537383177570094,-.4986107602930034,0,-.9692436362808796,1.8759675015077202,.04155505740717559,0,.05563007969699366,-.20397695888897652,1.0569715142428786,0,0,0,0,1]
PRESETS={'Aces2Hdr1000P3':'ACES-OUTPUT - ACES2065-1_to_CIE-XYZ-D65 - HDR-1000nit-P3-D65_2.0','AgXSdrRec2020':'AgX Base Rec.2020','AgXSdr':'AgX Base Rec.1886','AgXHdr1000':'AgX Rec.2100-HLG - HDR 1000 nits (P3 D65)','Aces2Sdr':'ACES-OUTPUT - ACES2065-1_to_CIE-XYZ-D65 - SDR-100nit-REC709_2.0','Aces2Hdr1000':'ACES-OUTPUT - ACES2065-1_to_CIE-XYZ-D65 - HDR-1000nit-REC2020_2.0'}
SOURCES={'LinearSrgb':('Linear Rec.709','Linear Rec.709 (sRGB)'), 'AcesCg':('ACEScg','ACEScg')}
PRESETS['FilmicSdr']='Filmic sRGB'
CHECK=False
def write(path,data):
    data=data.encode() if isinstance(data,str) else data
    if CHECK:
        if not path.exists() or path.read_bytes()!=data:raise SystemExit('Stale generated output: '+str(path))
    else:path.write_bytes(data)

def validate_inputs():
    pin=json.loads((ENG/'manifest.json').read_text())
    for item in pin['inputs']:
        path=ROOT/item['path']
        if hashlib.sha256(path.read_bytes()).hexdigest()!=item['sha256']:raise SystemExit('Input pin mismatch: '+item['path'])

HEADER='// Generated by eng/color-management/generate.py from pinned OpenColorIO 2.5.2.\n// OCIO BSD-3-Clause; AgX data licenses: ../BLENDER-LICENSE. Do not edit.\n'

def sampling(name,offset,w,h=1,d=1,linear=False):
    def fetch(x,y='0',z='0'):
        return f'mu3d_color_view_table[{offset} + clamp({x}, 0, {w-1}) + {w} * (clamp({y}, 0, {h-1}) + {h} * clamp({z}, 0, {d-1}))]'
    if d>1:return f'float4 {name}(float3 p) {{ return {fetch("int(floor(p.x * "+str(w)+".0))","int(floor(p.y * "+str(h)+".0))","int(floor(p.z * "+str(d)+".0))")}; }}\n'
    if not linear:return f'float4 {name}(float p) {{ return {fetch("int(floor(p * "+str(w)+".0))")}; }}\n'
    return f'''float4 {name}(float2 p) {{
 float px = p.x * {w}.0 - 0.5; float py = p.y * {h}.0 - 0.5;
 int x = int(floor(px)); int y = int(floor(py));
 return lerp(lerp({fetch('x','y')}, {fetch('x + 1','y')}, px - floor(px)), lerp({fetch('x','y + 1')}, {fetch('x + 1','y + 1')}, px - floor(px)), py - floor(py));
}}\n'''

def adapt(hlsl,desc):
    tables=[]; helpers=''; metadata=[]
    for t in list(desc.getTextures())+list(desc.get3DTextures()):
        vals=t.getValues().reshape(-1)
        three=hasattr(t,'edgeLen'); channels=3 if three or t.channel==ocio.GpuShaderDesc.TEXTURE_RGB_CHANNEL else 1
        # The binding exposes texture values in x-fastest GPU order, exactly as OCIO exported them.
        rgba=np.zeros((len(vals)//channels,4),dtype='<f4');rgba[:,:channels]=vals.reshape(-1,channels)
        offset=sum(len(v) for v in tables);tables.append(rgba)
        w=h=d=t.edgeLen if three else 1
        if not three:w,h=t.width,t.height
        linear=not three and t.interpolation==ocio.INTERP_LINEAR
        helpers+=sampling(t.textureName+'_sample_raw',offset,w,h,d,linear)
        metadata.append(dict(name=t.textureName,offset=offset,width=w,height=h,depth=d,interpolation='linear' if linear else 'nearest',channels=channels))
        hlsl=hlsl.replace(f'{t.textureName}.Sample({t.samplerName}, ',t.textureName+'_sample_raw(')
    hlsl=re.sub(r'^(?:Texture\w+|SamplerState) .*?;\n','',hlsl,flags=re.M)
    return helpers+hlsl,np.concatenate(tables),metadata

def csharp(text,name):
    text=re.sub(r'static const float (\w+)\[\d+\] =',r'private static readonly float[] \1 =',text)
    text=text.replace('mu3d_color_view_table[','Table[')
    text=re.sub(r'\b(float[234](?:x[234])?)\(',r'new \1(',text)
    text=re.sub(r'\b(float|int)\s*\(',r'(\1)(',text)
    # HLSL literals are float, C# unsuffixed decimal literals are double.
    text=re.sub(r'(?<![\w.])((?:\d+\.\d*|\.\d+)(?:[eE][+-]?\d+)?|\d+[eE][+-]?\d+)([fF]?)(?![\w.])',lambda m:(m[1]+'0' if m[1].endswith('.') else m[1])+'f',text)
    if '// Add JMh to RGB' in text:
        before, after = text.split('// Add JMh to RGB', 1)
        text = before + '// Add JMh to RGB' + re.sub(r'\b(JMh|Aab)\b', lambda m:m[1]+'_out', after)
    # Shader vectors are initialized even when components are assigned individually.
    text=re.sub(r'\b(float[234]) (\w+);',r'\1 \2 = default;',text)
    text=re.sub(r'\b(float[234]) (\w+), (\w+);',r'\1 \2 = default; \1 \3 = default;',text)
    text=re.sub(r'^(float\w* \w+\()',r'private \1',text,flags=re.M)
    text=text.replace('private float4 mu3d_color_view4(', 'internal override float4 Evaluate(')
    return HEADER+f'namespace Mu3D.Color;\ninternal sealed class {name}(System.Numerics.Vector4[] table) : ColorViewEvaluator(table)\n{{\n'+text+'\n}\n'

def processor(preset,source):
    blender=preset.startswith('AgX') or preset=='FilmicSdr'; c=ocio.Config.CreateFromFile(str(ENG/'upstream/blender/config.ocio')) if blender else ocio.Config.CreateFromBuiltinConfig('cg-config-v4.0.0_aces-v2.0_ocio-v2.5')
    group=ocio.GroupTransform()
    if blender:
        group.appendTransform(ocio.ColorSpaceTransform(src=SOURCES[source][0],dst='Linear CIE-XYZ E'))
        group.appendTransform(c.getViewTransform(PRESETS[preset]).getTransform(ocio.VIEWTRANSFORM_DIR_FROM_REFERENCE))
    else:
        group.appendTransform(ocio.ColorSpaceTransform(src=SOURCES[source][1],dst='ACES2065-1'))
        group.appendTransform(ocio.BuiltinTransform(style=PRESETS[preset]))
    group.appendTransform(ocio.MatrixTransform(matrix=XYZ))
    return c.getProcessor(group)

def display_reference(preset,source):
    # Independently select the user-facing official Display/View, then decode only
    # the display colorspace. Inverting the whole Display/View would erase the view.
    blender=preset.startswith('AgX') or preset=='FilmicSdr';hdr='Hdr' in preset
    c=ocio.Config.CreateFromFile(str(ENG/'upstream/blender/config.ocio')) if blender else ocio.Config.CreateFromBuiltinConfig('cg-config-v4.0.0_aces-v2.0_ocio-v2.5')
    display=('sRGB' if preset=='FilmicSdr' else 'Rec.2020' if preset=='AgXSdrRec2020' else 'Rec.2100-PQ' if hdr else 'Rec.1886') if blender else ('Rec.2100-PQ - Display' if hdr else 'sRGB - Display')
    view=('Filmic' if preset=='FilmicSdr' else 'AgX - HDR 1000 nits' if hdr else 'AgX') if blender else ('ACES 2.0 - HDR 1000 nits (P3 D65)' if preset=='Aces2Hdr1000P3' else 'ACES 2.0 - HDR 1000 nits (Rec.2020)' if hdr else 'ACES 2.0 - SDR 100 nits (Rec.709)')
    g=ocio.GroupTransform()
    g.appendTransform(ocio.DisplayViewTransform(src=SOURCES[source][0 if blender else 1],display=display,view=view))
    # Wrap rather than mutating the config-owned transform's direction.
    g.appendTransform(ocio.GroupTransform([c.getColorSpace(display).getTransform(ocio.COLORSPACE_DIR_FROM_REFERENCE)],direction=ocio.TRANSFORM_DIR_INVERSE))
    g.appendTransform(ocio.MatrixTransform(matrix=XYZ))
    return c.getProcessor(g).getDefaultCPUProcessor()

def main():
    global CHECK,ocio,np
    ap=argparse.ArgumentParser();ap.add_argument('--slangc');ap.add_argument('--check',action='store_true');ap.add_argument('--validate-input-pins',action='store_true');args=ap.parse_args()
    validate_inputs()
    if args.validate_input_pins and not args.slangc:return
    if not args.slangc:ap.error('--slangc is required to generate programs')
    import PyOpenColorIO as ocio
    import numpy as np
    if np.__version__!='2.4.3':raise SystemExit('Exact NumPy 2.4.3 required')
    pin=json.loads((ENG/'manifest.json').read_text())
    if hashlib.sha256(pathlib.Path(args.slangc).read_bytes()).hexdigest()!=pin['slang']['executableSha256']:raise SystemExit('Slang compiler pin mismatch')
    compiler_library=pathlib.Path(args.slangc).resolve().parent.parent/'lib/libslang-compiler.0.2026.14.dylib'
    if hashlib.sha256(compiler_library.read_bytes()).hexdigest()!=pin['slang']['librarySha256']:raise SystemExit('Slang library pin mismatch')
    module_dir=pathlib.Path(ocio.__file__).parent
    for filename,key in [('PyOpenColorIO.so','moduleSha256'),('libOpenColorIO.dylib','librarySha256')]:
        if hashlib.sha256((module_dir/filename).read_bytes()).hexdigest()!=pin['ocio'][key]:raise SystemExit('Pinned OCIO wheel module mismatch: '+filename)
    CHECK=args.check
    if ocio.GetVersion()!='2.5.2':raise SystemExit('Exact OpenColorIO 2.5.2 required')
    OUT.mkdir(parents=True,exist_ok=True)
    fixtures={};outputs={}
    for preset in PRESETS:
      for source in SOURCES:
        name=preset+source;p=processor(preset,source)
        desc=ocio.GpuShaderDesc.CreateShaderDesc();desc.setLanguage(ocio.GPU_LANGUAGE_HLSL_DX11);desc.setFunctionName('mu3d_color_view4');p.getDefaultGPUProcessor().extractGpuShaderInfo(desc)
        adapted,table,metadata=adapt(desc.getShaderText(),desc)
        write(OUT/(name+'.g.cs'),csharp(adapted,name))
        write(OUT/(preset+'.bin'),table.tobytes())
        write(OUT/(preset+'.tables.json'),json.dumps(metadata,indent=2)+'\n')
        hlsl='[[vk::binding(0,1)]] StructuredBuffer<float4> mu3d_color_view_table;\n'+adapted+'\n[[vk::binding(0,0)]] RWStructuredBuffer<float4> probe;\n[shader("compute")][numthreads(1,1,1)] void main() { probe[0] = mu3d_color_view4(probe[1]); }\n'
        with tempfile.TemporaryDirectory(prefix='mu3d-color-') as td:
            inp=pathlib.Path(td)/'view.slang';out=pathlib.Path(td)/'view.wgsl';inp.write_text(hlsl)
            subprocess.run([args.slangc,str(inp),'-entry','main','-target','wgsl','-O0','-o',str(out)],check=True)
            wgsl=out.read_text()
        # Keep the generated callable evaluator but omit the maintainer-only compute probe entry.
        wgsl=re.sub(r'@binding\(0\) @group\(0\)\s*var<storage, read_write> probe[^;]*;\n','',wgsl)
        wgsl=re.sub(r'@compute[\s\S]*$', '',wgsl)
        entry=re.search(r'fn (mu3d_color_view4\w*)\(',wgsl)[1]
        wgsl+='\nfn mu3d_color_view(rgb: vec3<f32>) -> vec3<f32> { return '+entry+'(vec4<f32>(rgb, 1.0)).xyz; }\n'
        write(OUT/(name+'.wgsl'),HEADER+wgsl)
        # Independent official CPU processor, not the translated GPU function.
        cpu=p.getDefaultCPUProcessor()
        cases=[[0,0,0],[.18,.18,.18],[1,1,1],[16,16,16],[1024,1024,1024],[-.1,.2,.7],[1,0,0],[0,1,0],[0,0,1],[20,.01,.001],[.001,20,.01],[.01,.001,20]]
        rng=np.random.default_rng(752)
        cases+=list((np.exp2(rng.uniform(-14,12,(256,3)))*rng.choice([-1,1],(256,3),p=[.05,.95])).tolist())
        official_display=display_reference(preset,source)
        for value in cases:
            if max(abs(a-b) for a,b in zip(cpu.applyRGB(value),official_display.applyRGB(value)))>1e-6:raise SystemExit('Display reference mismatch: '+name)
        fixtures[name]=[dict(input=v,output=cpu.applyRGB(v)) for v in cases]
        outputs[name]=dict(shaderSha256=hashlib.sha256((OUT/(name+'.wgsl')).read_bytes()).hexdigest(),tableSha256=hashlib.sha256(table.tobytes()).hexdigest())
        print(name,'table',len(table),'shader',len(wgsl),flush=True)
    write(ROOT/'tests/Mu3D.Color.Views.Tests/Reference/ocio-2.5.2.json',json.dumps(fixtures,separators=(',',':'))+'\n')
    write(OUT/'manifest.json',json.dumps(outputs,indent=2)+'\n')
if __name__=='__main__':main()
