if(NOT DEFINED MU3D_APPLE_ARCH AND DEFINED ENV{MU3D_APPLE_ARCH})
  set(MU3D_APPLE_ARCH "$ENV{MU3D_APPLE_ARCH}")
endif()

if(NOT DEFINED MU3D_APPLE_PLATFORM AND DEFINED ENV{MU3D_APPLE_PLATFORM})
  set(MU3D_APPLE_PLATFORM "$ENV{MU3D_APPLE_PLATFORM}")
endif()

if(NOT MU3D_APPLE_ARCH STREQUAL "arm64" AND NOT MU3D_APPLE_ARCH STREQUAL "x86_64")
  message(FATAL_ERROR "MU3D_APPLE_ARCH must be arm64 or x86_64")
endif()

if(MU3D_APPLE_PLATFORM STREQUAL "ios")
  if(NOT MU3D_APPLE_ARCH STREQUAL "arm64")
    message(FATAL_ERROR "Physical iOS builds require arm64")
  endif()
  set(MU3D_APPLE_SDK iphoneos)
  set(MU3D_APPLE_TARGET "arm64-apple-ios15.0")
elseif(MU3D_APPLE_PLATFORM STREQUAL "iossimulator")
  set(MU3D_APPLE_SDK iphonesimulator)
  set(MU3D_APPLE_TARGET "${MU3D_APPLE_ARCH}-apple-ios15.0-simulator")
elseif(MU3D_APPLE_PLATFORM STREQUAL "maccatalyst")
  set(MU3D_APPLE_SDK macosx)
  set(MU3D_APPLE_TARGET "${MU3D_APPLE_ARCH}-apple-ios15.0-macabi")
else()
  message(FATAL_ERROR "MU3D_APPLE_PLATFORM must be ios, iossimulator or maccatalyst")
endif()

set(MU3D_APPLE_ARCH "${MU3D_APPLE_ARCH}" CACHE STRING "Apple target architecture")
set(MU3D_APPLE_PLATFORM "${MU3D_APPLE_PLATFORM}" CACHE STRING "Apple target platform")
set(CMAKE_TRY_COMPILE_PLATFORM_VARIABLES MU3D_APPLE_ARCH MU3D_APPLE_PLATFORM)

execute_process(
  COMMAND xcrun --sdk "${MU3D_APPLE_SDK}" --show-sdk-path
  OUTPUT_VARIABLE MU3D_APPLE_SYSROOT
  OUTPUT_STRIP_TRAILING_WHITESPACE
  COMMAND_ERROR_IS_FATAL ANY)

set(CMAKE_SYSTEM_NAME Darwin)
set(CMAKE_SYSTEM_PROCESSOR "${MU3D_APPLE_ARCH}")
set(CMAKE_OSX_ARCHITECTURES "${MU3D_APPLE_ARCH}")
set(CMAKE_OSX_SYSROOT "${MU3D_APPLE_SYSROOT}")
set(CMAKE_OSX_DEPLOYMENT_TARGET 15.0)
set(CMAKE_C_COMPILER clang)
set(CMAKE_CXX_COMPILER clang++)
set(CMAKE_C_COMPILER_TARGET "${MU3D_APPLE_TARGET}")
set(CMAKE_CXX_COMPILER_TARGET "${MU3D_APPLE_TARGET}")
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
