if(NOT DEFINED MU3D_APPLE_ARCH AND DEFINED ENV{MU3D_APPLE_ARCH})
  set(MU3D_APPLE_ARCH "$ENV{MU3D_APPLE_ARCH}")
endif()

if(NOT DEFINED MU3D_APPLE_ARCH)
  message(FATAL_ERROR "MU3D_APPLE_ARCH must be arm64 or x86_64")
endif()

if(NOT MU3D_APPLE_ARCH STREQUAL "arm64" AND NOT MU3D_APPLE_ARCH STREQUAL "x86_64")
  message(FATAL_ERROR "Unsupported Mac Catalyst architecture: ${MU3D_APPLE_ARCH}")
endif()

set(MU3D_APPLE_ARCH "${MU3D_APPLE_ARCH}" CACHE STRING "Mac Catalyst architecture")
set(CMAKE_TRY_COMPILE_PLATFORM_VARIABLES MU3D_APPLE_ARCH)

execute_process(
  COMMAND xcrun --sdk macosx --show-sdk-path
  OUTPUT_VARIABLE MU3D_MACOS_SDK
  OUTPUT_STRIP_TRAILING_WHITESPACE
  COMMAND_ERROR_IS_FATAL ANY)

set(CMAKE_SYSTEM_NAME Darwin)
set(CMAKE_SYSTEM_PROCESSOR "${MU3D_APPLE_ARCH}")
set(CMAKE_OSX_ARCHITECTURES "${MU3D_APPLE_ARCH}")
set(CMAKE_OSX_SYSROOT "${MU3D_MACOS_SDK}")
set(CMAKE_OSX_DEPLOYMENT_TARGET 15.0)
set(CMAKE_C_COMPILER clang)
set(CMAKE_CXX_COMPILER clang++)
set(CMAKE_C_COMPILER_TARGET "${MU3D_APPLE_ARCH}-apple-ios15.0-macabi")
set(CMAKE_CXX_COMPILER_TARGET "${MU3D_APPLE_ARCH}-apple-ios15.0-macabi")
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
