<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <IncludeSymbols>false</IncludeSymbols>
    <IsPackable>true</IsPackable>
    <SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
    <Authors>Mu3D</Authors>
    <Company>Mu3D</Company>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>Mu3D;native;runtime;MAUI</PackageTags>
    <PublishRepositoryUrl>false</PublishRepositoryUrl>
    <EmbedUntrackedSources>false</EmbedUntrackedSources>
    <DebugType>none</DebugType>
    <NoWarn>$(NoWarn);NU5100;NU5128</NoWarn>
  </PropertyGroup>
</Project>
