using System.Buffers.Binary;
using System.Text;
using System.Security.Cryptography;

namespace Mu3D.Color;

/// <summary>Provides deterministic ICC v4 matrix/TRC profiles for standard encoded RGB interchange.</summary>
/// <remarks>These describe mathematical RGB encodings, not measured monitors. Colorants are Bradford
/// adapted to D50. Fixed-point ICC quantization is approximate; use the parametric converter for FP32
/// intermediate processing. Profiles contain no perceptual gamut-mapping tables.</remarks>
public static class StandardRgbProfiles
{
    private static readonly Lazy<IccProfile>[] Profiles = Enum.GetValues<StandardRgbEncoding>()
        .Select(encoding => new Lazy<IccProfile>(() => Create(encoding))).ToArray();

    /// <summary>Gets an immutable, cached profile suitable for embedding in ordinary RGB image files.</summary>
    public static IccProfile Get(StandardRgbEncoding encoding)
    {
        _ = StandardRgbEncodingConverter.GetLinearSpace(encoding);
        return Profiles[(int)encoding].Value;
    }

    private static IccProfile Create(StandardRgbEncoding encoding)
    {
        var space = StandardRgbEncodingConverter.GetLinearSpace(encoding);
        byte[] curve = Curve(encoding);
        List<(string Name, byte[] Data)> tags =
        [
            ("desc", Text($"Mu3D {encoding} RGB encoding")),
            ("cprt", Text("Public domain mathematical color-space definition; generated by Mu3D.")),
            ("wtpt", FixedTag("XYZ ", [0.9642f, 1, 0.8249f])),
            ("chad", FixedTag("sf32", StandardLinearRgbConverter.GetD50Adaptation(space.Space))),
        ];
        for (int i = 0; i < 3; i++)
        {
            var xyz = StandardLinearRgbConverter.ToXyzD50(
                new(i == 0 ? 1 : 0, i == 1 ? 1 : 0, i == 2 ? 1 : 0, 1, space), space);
            tags.Add(($"{"rgb"[i]}XYZ", FixedTag("XYZ ", [xyz.X, xyz.Y, xyz.Z])));
            tags.Add(($"{"rgb"[i]}TRC", curve));
        }
        int offset = 132 + tags.Count * 12;
        byte[] bytes = new byte[offset + tags.Sum(t => (t.Data.Length + 3) & ~3)];
        U32(bytes, 0, (uint)bytes.Length);
        U32(bytes, 8, 0x04300000);
        Signature(bytes, 12, "mntr"); Signature(bytes, 16, "RGB "); Signature(bytes, 20, "XYZ ");
        // Fixed creation date keeps profile fingerprints deterministic across builds.
        ushort[] date = [2026, 9, 18, 0, 0, 0];
        for (int i = 0; i < date.Length; i++) BinaryPrimitives.WriteUInt16BigEndian(bytes.AsSpan(24 + 2 * i), date[i]);
        Signature(bytes, 36, "acsp"); U32(bytes, 64, 1);
        Fixed(bytes, 68, 0.9642f); Fixed(bytes, 72, 1); Fixed(bytes, 76, 0.8249f);
        Signature(bytes, 80, "Mu3D"); U32(bytes, 128, (uint)tags.Count);
        for (int i = 0; i < tags.Count; i++)
        {
            var tag = tags[i]; int entry = 132 + 12 * i;
            Signature(bytes, entry, tag.Name); U32(bytes, entry + 4, (uint)offset);
            U32(bytes, entry + 8, (uint)tag.Data.Length);
            tag.Data.CopyTo(bytes, offset); offset += (tag.Data.Length + 3) & ~3;
        }
        // ICC v4 profile ID uses MD5 with flags, rendering intent and profile ID zeroed.
        byte[] hashInput = (byte[])bytes.Clone();
        hashInput.AsSpan(44, 4).Clear();
        hashInput.AsSpan(64, 4).Clear();
        hashInput.AsSpan(84, 16).Clear();
        MD5.HashData(hashInput).CopyTo(bytes, 84);
        return new IccProfile(bytes);
    }

    private static byte[] Curve(StandardRgbEncoding encoding)
    {
        float[] parameters = encoding switch
        {
            StandardRgbEncoding.Srgb or StandardRgbEncoding.DisplayP3 => [2.4f, 1 / 1.055f, 0.055f / 1.055f, 1 / 12.92f, 0.04045f],
            StandardRgbEncoding.AdobeRgb => [563f / 256f],
            StandardRgbEncoding.ProPhotoRgb => [1.8f, 1, 0, 1 / 16f, 1 / 32f],
            // Type 4 with zero offsets is equivalent to type 3. Apple ColorSync substitutes
            // a display-EOTF result for the type-3 BT.2020 curve; type 4 preserves this OETF.
            StandardRgbEncoding.Rec2020 => [1 / 0.45f, 1 / 1.09929682680944f, 0.09929682680944f / 1.09929682680944f,
                1 / 4.5f, 4.5f * 0.018053968510807f, 0, 0],
            _ => throw new ArgumentOutOfRangeException(nameof(encoding)),
        };
        byte[] bytes = new byte[12 + parameters.Length * 4];
        Signature(bytes, 0, "para");
        BinaryPrimitives.WriteUInt16BigEndian(bytes.AsSpan(8), parameters.Length == 1 ? (ushort)0 : parameters.Length == 7 ? (ushort)4 : (ushort)3);
        for (int i = 0; i < parameters.Length; i++) Fixed(bytes, 12 + 4 * i, parameters[i]);
        return bytes;
    }

    private static byte[] FixedTag(string type, float[] values)
    {
        byte[] bytes = new byte[8 + values.Length * 4]; Signature(bytes, 0, type);
        for (int i = 0; i < values.Length; i++) Fixed(bytes, 8 + 4 * i, values[i]);
        return bytes;
    }
    private static byte[] Text(string text)
    {
        byte[] payload = Encoding.BigEndianUnicode.GetBytes(text);
        byte[] bytes = new byte[28 + payload.Length]; Signature(bytes, 0, "mluc");
        U32(bytes, 8, 1); U32(bytes, 12, 12); Signature(bytes, 16, "enUS");
        U32(bytes, 20, (uint)payload.Length); U32(bytes, 24, 28); payload.CopyTo(bytes, 28);
        return bytes;
    }
    private static void Signature(byte[] bytes, int offset, string value) => Encoding.ASCII.GetBytes(value).CopyTo(bytes, offset);
    private static void U32(byte[] bytes, int offset, uint value) => BinaryPrimitives.WriteUInt32BigEndian(bytes.AsSpan(offset), value);
    private static void Fixed(byte[] bytes, int offset, float value) =>
        BinaryPrimitives.WriteInt32BigEndian(bytes.AsSpan(offset), checked((int)MathF.Round(value * 65536)));
}
