using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;

namespace Mu3D.WgpuGen;

internal static partial class ClangSharpPostProcessor
{
    internal const int ExpectedEnumCount = 70;
    internal const int ExpectedStructCount = 137;
    internal const int ExpectedFunctionCount = 228;

    private const string DllImport =
        "[DllImport(\"wgpu_native\", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]";
    private const string LibraryImport =
        "[LibraryImport(\"wgpu_native\")]\n        " +
        "[UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]";

    public static string Process(string rawSource, string webGpuHeaderPath, string wgpuHeaderPath)
    {
        rawSource = rawSource.ReplaceLineEndings("\n");
        ValidateShape(rawSource);

        string source = rawSource
            .Replace(DllImport, LibraryImport, StringComparison.Ordinal)
            .Replace("public static extern ", "internal static partial ", StringComparison.Ordinal);

        const string namespaceOpening = "namespace Mu3D.Native.Wgpu.Interop\n{";
        string identity = $$"""
            namespace Mu3D.Native.Wgpu.Interop
            {
                internal static class WgpuHeaderIdentity
                {
                    internal const string WebGpuHeaderSha256 = "{{HashFile(webGpuHeaderPath)}}";
                    internal const string WgpuHeaderSha256 = "{{HashFile(wgpuHeaderPath)}}";
                }
            """;

        if (!source.Contains(namespaceOpening, StringComparison.Ordinal))
        {
            throw new InvalidDataException("ClangSharp output does not contain the expected namespace.");
        }

        source = source.Replace(namespaceOpening, identity, StringComparison.Ordinal);
        return "// <auto-generated />\n#pragma warning disable CS0649\n" + source.TrimEnd() + "\n";
    }

    public static void Write(
        string rawSource,
        string webGpuHeaderPath,
        string wgpuHeaderPath,
        string outputPath)
    {
        string source = Process(rawSource, webGpuHeaderPath, wgpuHeaderPath);
        string? directory = Path.GetDirectoryName(Path.GetFullPath(outputPath));
        Directory.CreateDirectory(directory!);
        File.WriteAllText(outputPath, source, new UTF8Encoding(false));
    }

    private static void ValidateShape(string source)
    {
        int enumCount = EnumDeclarationRegex().Count(source);
        int structCount = StructDeclarationRegex().Count(source);
        int importCount = CountOccurrences(source, DllImport);
        int functionCount = CountOccurrences(source, "public static extern ");

        if (enumCount != ExpectedEnumCount ||
            structCount != ExpectedStructCount ||
            importCount != ExpectedFunctionCount ||
            functionCount != ExpectedFunctionCount)
        {
            throw new InvalidDataException(
                "Pinned wgpu-native header shape changed: " +
                $"expected {ExpectedEnumCount} enums, {ExpectedStructCount} structs and " +
                $"{ExpectedFunctionCount} functions; got {enumCount}, {structCount}, " +
                $"{functionCount} functions and {importCount} imports.");
        }
    }

    private static string HashFile(string path)
    {
        using FileStream stream = File.OpenRead(path);
        return Convert.ToHexStringLower(SHA256.HashData(stream));
    }

    private static int CountOccurrences(string source, string value)
    {
        int count = 0;
        int startIndex = 0;
        while ((startIndex = source.IndexOf(value, startIndex, StringComparison.Ordinal)) >= 0)
        {
            count++;
            startIndex += value.Length;
        }

        return count;
    }

    [GeneratedRegex(@"(?m)^    internal enum ")]
    private static partial Regex EnumDeclarationRegex();

    [GeneratedRegex(@"(?m)^    internal (?:unsafe )?partial struct ")]
    private static partial Regex StructDeclarationRegex();
}
