using System.Security.Cryptography;
using System.Text;

namespace Mu3D.WgpuGen;

internal static class MetadataEmitter
{
    public static void Write(NativeAssetManifest manifest, string manifestPath, string outputPath)
    {
        string manifestHash = Convert.ToHexStringLower(SHA256.HashData(File.ReadAllBytes(manifestPath)));
        string source = $$"""
            // <auto-generated />
            namespace Mu3D.Native.Wgpu.Interop;

            internal static class WgpuNativeBuildInfo
            {
                internal const string Version = "{{manifest.Upstream.Tag}}";
                internal const string Commit = "{{manifest.Upstream.Commit}}";
                internal const string ManifestSha256 = "{{manifestHash}}";
            }
            """;

        string? directory = Path.GetDirectoryName(Path.GetFullPath(outputPath));
        Directory.CreateDirectory(directory!);
        File.WriteAllText(outputPath, source + Environment.NewLine, new UTF8Encoding(false));
    }
}
